import os
import hashlib
from loguru import logger
from agent_universe.base_agent import BaseAgent

class CoderAgent(BaseAgent):
    """
    Responsibilities:
    - Generate Python tool code using LLMBrain
    - Follow strict tool template
    - Output structured code
    """
    def __init__(self):
        super().__init__(name="Coder-01", role="System Architect & Coder")
        self.template = """from tools.base_tool import BaseTool
from loguru import logger

class {class_name}(BaseTool):
    def __init__(self):
        super().__init__(
            name="{tool_name}",
            description="{description}"
        )

    async def execute(self, **kwargs):
        # Optimized implementation generated by CoderAgent
{implementation}
        return {{"status": "success", "data": "Protocol execution verified."}}
"""

    async def generate_tool(self, tool_requirement: str):
        """Generates a functional Python tool based on requirements."""
        logger.info("Jules AI: Drafting architectural code for requirement: {}", tool_requirement)

        prompt = (
            f"Requirement: '{tool_requirement}'\n"
            "Action: Generate functional Python code for the 'execute' method of a BaseTool subclass.\n"
            "Constraints: No external imports, use 'logger' for output, return structured dict.\n"
            "Indentation: 8 spaces."
        )

        implementation = await self.llm.reason(prompt)

        # Cleanup
        if "```python" in implementation:
            implementation = implementation.split("```python")[1].split("```")[0]
        elif "```" in implementation:
            implementation = implementation.split("```")[1].split("```")[0]

        tool_name = f"GenTool_{hashlib.md5(tool_requirement.encode()).hexdigest()[:8]}"
        class_name = tool_name
        description = f"Autonomous logic unit for: {tool_requirement}"

        if not implementation.strip() or "pass" in implementation.lower():
            implementation = "        logger.info('Executing default logic sequence.')\n        return {'status': 'success'}"

        if not implementation.startswith("        "):
            lines = implementation.split("\n")
            implementation = "\n".join(["        " + line if line.strip() else line for line in lines])

        code = self.template.format(
            class_name=class_name,
            tool_name=tool_name,
            description=description,
            implementation=implementation
        )

        return {"name": tool_name, "code": code, "description": description}

    async def save_tool(self, tool_data: dict):
        """Saves the logic to the generated tools repository."""
        filename = f"tool_{hashlib.md5(tool_data['name'].encode()).hexdigest()[:8]}.py"
        filepath = os.path.join("tools", "generated", filename)
        os.makedirs(os.path.dirname(filepath), exist_ok=True)

        with open(filepath, "w") as f:
            f.write(tool_data["code"])

        logger.success("Logic unit synchronized to {}", filepath)
        return filepath
