# Generated by Django 6.0.3 on 2026-03-15 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50)),
                ("module", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=50)),
                ("target_id", models.CharField(max_length=100)),
                ("old_value", models.JSONField(null=True)),
                ("new_value", models.JSONField(null=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("device_fingerprint", models.TextField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
