# Generated by Django 6.0.3 on 2026-03-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit_log", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-timestamp"],
                "permissions": [("view_audit_logs", "Can view audit logs")],
            },
        ),
    ]
