# Generated by Django 6.0.3 on 2026-03-15 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("erp_core", "0001_initial"),
        ("master_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Advance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "repayment_type",
                    models.CharField(
                        choices=[
                            ("AUTO", "Auto"),
                            ("EMI", "EMI"),
                            ("MANUAL", "Manual"),
                        ],
                        default="AUTO",
                        max_length=20,
                    ),
                ),
                (
                    "emi_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_fully_paid", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp_core.employee",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_data.unit",
                    ),
                ),
            ],
        ),
    ]
