# Generated by Django 6.0.3 on 2026-03-15 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_core", "0001_initial"),
        ("master_data", "0001_initial"),
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                (
                    "production_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "attendance_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "overtime_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "advance_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp_core.employee",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_data.unit",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "month", "year")},
            },
        ),
    ]
