# Generated by Django 6.0.3 on 2026-03-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_core", "0002_alter_employee_employee_id"),
        ("master_data", "0001_initial"),
        ("payroll", "0002_salaryrecord"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="salaryrecord",
            index=models.Index(
                fields=["employee", "month", "year"],
                name="payroll_sal_employe_477703_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salaryrecord",
            index=models.Index(
                fields=["unit", "month", "year"], name="payroll_sal_unit_id_0b909b_idx"
            ),
        ),
    ]
