# Generated by Django 6.0.3 on 2026-03-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
