# Generated by Django 6.0.3 on 2026-03-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionentry",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
