# Generated by Django 6.0.3 on 2026-03-15 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_core", "0002_alter_employee_employee_id"),
        ("master_data", "0001_initial"),
        ("production", "0002_alter_productionentry_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyProductionSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_quantity", models.IntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("employee_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddIndex(
            model_name="productionentry",
            index=models.Index(
                fields=["unit", "date"], name="production__unit_id_327b37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionentry",
            index=models.Index(
                fields=["employee", "date"], name="production__employe_ff75c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionentry",
            index=models.Index(
                fields=["buyer", "date"], name="production__buyer_i_e48207_idx"
            ),
        ),
        migrations.AddField(
            model_name="dailyproductionsummary",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="master_data.unit"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyproductionsummary",
            index=models.Index(
                fields=["unit", "date"], name="production__unit_id_d25a31_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyproductionsummary",
            unique_together={("unit", "date")},
        ),
    ]
